from pathlib import Path
import json
p=Path(__file__).resolve().parents[1]
prompts={'Build (both runs)': 'Build Aggie Launchpad for the fictional Campus Cycle founder using the files in this workspace. Create a self-contained local index.html dashboard connecting the venture hypothesis, customer evidence, experiment, decision status, and next owner. Include an editable reservation record and save a Markdown handoff another teammate can continue. Use maroon and cream accents, accessible controls, and light/dark mode. Work without a build step or network. Check your work and preserve uncertainty. Do not contact anyone, schedule real repairs, collect payments, publish, or connect to live accounts.', 'Buzz review (both runs)': 'Review the Aggie Launchpad dashboard and handoff against the supplied source. Distinguish observations from assumptions, check active reservations against the target, and identify the next decision and owner. Prepare a handoff for another teammate. Keep all work in this demo room; do not contact anyone or change external systems.', 'Exception (both runs)': 'Update U-01: reservations P05 and P06 have been canceled. Nothing else has changed. Update the experiment, preserve original evidence and history, and show the current status and next decision owner. Do not change the agreed target or invent a founder decision.', 'Continuation (both runs)': 'I am taking over research for Campus Cycle. What have we observed, what remains an assumption, what changed, and what decision does Jordan need to make next? Continue from the saved work, cite its sources, and do not invent an approval.'}
checks=['Hypothesis and scope', 'Interest versus reservations', 'Untested paid demand', 'Target and current count', 'Decision authority', 'Cancellation handling', 'Sources and history', 'Fresh-session continuation']
head='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Aggie Launchpad · Demo console</title><style>:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:#071016;color:#edf6fb;font:16px/1.55 Roboto,system-ui,sans-serif}main{max-width:1150px;margin:auto;padding:40px 24px}h1{font-size:46px;line-height:1.1}h2{margin-top:40px}p,small{color:#a3bccd}a{color:#5eead4}nav{display:flex;gap:24px;flex-wrap:wrap}article{background:#0d1821;border:1px solid #294657;padding:22px;margin:18px 0;border-radius:8px}button{background:#143f46;border:1px solid #5eead4;border-radius:5px;color:#edf6fb;padding:9px 14px;font:inherit;cursor:pointer}button:focus-visible,a:focus-visible,select:focus-visible,textarea:focus-visible{outline:3px solid #e8c589;outline-offset:4px}pre{white-space:pre-wrap;font:16px/1.6 ui-monospace,monospace}table{width:100%;border-collapse:collapse}td,th{padding:12px;border-bottom:1px solid #294657;text-align:left}select,textarea{background:#102430;color:#edf6fb;border:1px solid #294657;padding:8px;font:inherit}textarea{width:100%;min-height:55px}select{min-width:80px}.scroll{overflow-x:auto}.notice{border-left:3px solid #e8c589;padding:16px;background:#19262e}.timer{font:40px ui-monospace,monospace;margin-right:20px}.tools{display:flex;gap:12px;align-items:center;flex-wrap:wrap}#status{min-height:24px;color:#5eead4}label{display:block}@media(max-width:650px){h1{font-size:34px}td,th{padding:7px}table{min-width:650px}}</style></head><body><main><nav><a href="../slides.html">Slides</a><a href="reference-app/index.html" target="_blank" rel="noopener noreferrer">Reference app</a><a href="source/venture-brief.md">Source brief</a><a href="context/README.md">Operating packet</a></nav><h1>Same task. Same checks.<br>Two starting points.</h1><p>Presenter console · Aggie Launchpad</p><div class="notice">The reference app is illustrative. Scores stay blank until real runs produce evidence. Record actual tool/model versions and inherited context before comparing.</div><h2>Segment timer</h2><div class="tools"><span class="timer" id="timer">00:00</span><button id="start">Start / pause</button><button id="restart">Restart timer</button></div><h2>Shared prompts</h2>'''
body=''
from html import escape
for i,(title,prompt) in enumerate(prompts.items()):body+=f'<article><h3>{escape(title)}</h3><pre id="prompt{i}">{escape(prompt)}</pre><button data-copy="prompt{i}">Copy prompt</button></article>'
body+='<p id="status" role="status"></p><h2>Evidence rubric</h2><p>0 = missing/wrong · 1 = partial · 2 = correct with evidence. Maximum 16 per condition.</p><div class="scroll"><table><thead><tr><th>Check</th><th>Raw brief</th><th>Operating packet</th><th>Evidence / timestamp</th></tr></thead><tbody>'
for i,c in enumerate(checks):
 body+='<tr><th>'+c+'</th>'
 for condition in ['baseline','framework']:body+=f'<td><select aria-label="{c}: {condition}" data-score="{condition}"><option value="">—</option><option>0</option><option>1</option><option>2</option></select></td>'
 body+=f'<td><textarea aria-label="{c}: evidence"></textarea></td></tr>'
body+='</tbody></table></div><p id="totals">Scores not recorded.</p><label for="run-notes">Run details: model, tool version, time, corrections, inherited context</label><textarea id="run-notes"></textarea><p><button id="export">Export evidence</button></p><p>Scorecard is kept in memory only. Export before closing this page. See the demo script for isolation, source parity, and rehearsal capture.</p></main>'
js='''<script>const $=id=>document.getElementById(id);let running=false,elapsed=0,start=0;function tick(){const secs=Math.floor((elapsed+(running?Date.now()-start:0))/1000);$('timer').textContent=String(Math.floor(secs/60)).padStart(2,'0')+':'+String(secs%60).padStart(2,'0')}setInterval(tick,250);$('start').onclick=()=>{if(running){elapsed+=Date.now()-start;running=false}else{start=Date.now();running=true}tick()};$('restart').onclick=()=>{elapsed=0;start=Date.now();tick()};document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{try{await navigator.clipboard.writeText($(b.dataset.copy).textContent);$('status').textContent='Prompt copied.'}catch{$('status').textContent='Clipboard unavailable. Select and copy the prompt text.'}});document.querySelectorAll('select').forEach(s=>s.onchange=()=>{$('totals').textContent=['baseline','framework'].map(c=>{const a=[...document.querySelectorAll(`[data-score="${c}"]`)];const filled=a.filter(x=>x.value!=='');return c+': '+filled.reduce((n,x)=>n+Number(x.value),0)+'/16 ('+filled.length+'/8 scored)'}).join(' · ')});$('export').onclick=()=>{const rows=[...document.querySelectorAll('tbody tr')].map(r=>({criterion:r.querySelector('th').textContent,baseline:r.querySelector('[data-score="baseline"]').value,framework:r.querySelector('[data-score="framework"]').value,evidence:r.querySelector('textarea').value}));const data={capturedAt:new Date().toISOString(),notes:$('run-notes').value,rows};const u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download='aggie-launchpad-evidence.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};</script></body></html>'''
(p/'demo/index.html').write_text(head+body+js)
(p/'demo/prompts.json').write_text(json.dumps(prompts,indent=2)+'\n')
